## Project initialization and setup tasks
## Variables are defined in make/commons.mk

.PHONY: setup setup.env

setup.env: ## Generate .tooling.env with unique project ID (non-interactive)
	@if [ -f .tooling.env ]; then \
		echo ".tooling.env already exists"; \
		source .tooling.env; \
		echo "  PROJECT_ID: $$PROJECT_ID"; \
	else \
		echo "Generating unique project identifier..."; \
		PROJECT_ID=$$(echo "$(REPO_DIRNAME)-$$(echo -n $(REPO_ROOT) | sha256sum | cut -c1-8)"); \
		echo "# Project Tooling Configuration" > .tooling.env; \
		echo "# Auto-generated by 'make setup.env'" >> .tooling.env; \
		echo "# DO NOT COMMIT - contains local checkout-specific settings" >> .tooling.env; \
		echo "" >> .tooling.env; \
		echo "# Unique project identifier" >> .tooling.env; \
		echo "PROJECT_ID=$$PROJECT_ID" >> .tooling.env; \
		echo "" >> .tooling.env; \
		echo "# Docker Compose project name" >> .tooling.env; \
		echo "COMPOSE_PROJECT_NAME=$$PROJECT_ID" >> .tooling.env; \
		echo "" >> .tooling.env; \
		echo "Created .tooling.env"; \
		echo "  PROJECT_ID: $$PROJECT_ID"; \
	fi

setup: ## Interactive project setup
	@echo "repo-base - Interactive Project Setup"
	@echo ""
	@if [ -f .tooling.env ]; then \
		echo ".tooling.env already exists. Skipping setup."; \
		source .tooling.env; \
		echo "  Current PROJECT_ID: $$PROJECT_ID"; \
		echo ""; \
		echo "To reconfigure, delete .tooling.env and run 'make setup' again."; \
		echo ""; \
		exit 0; \
	fi; \
	echo "This will generate .tooling.env with a unique PROJECT_ID for your project."; \
	echo ""; \
	read -p "Enter project name [$(REPO_DIRNAME)]: " project_name; \
	project_name=$${project_name:-$(REPO_DIRNAME)}; \
	echo ""; \
	echo "Project name: $$project_name"; \
	echo ""; \
	echo "Generating .tooling.env..."; \
	PROJECT_ID=$$(echo "$$project_name-$$(echo -n $(REPO_ROOT) | sha256sum | cut -c1-8)"); \
	echo "# Project Tooling Configuration" > .tooling.env; \
	echo "# Auto-generated by 'make setup'" >> .tooling.env; \
	echo "# DO NOT COMMIT - contains local checkout-specific settings" >> .tooling.env; \
	echo "" >> .tooling.env; \
	echo "# Unique project identifier" >> .tooling.env; \
	echo "PROJECT_ID=$$PROJECT_ID" >> .tooling.env; \
	echo "" >> .tooling.env; \
	echo "# Docker Compose project name" >> .tooling.env; \
	echo "COMPOSE_PROJECT_NAME=$$PROJECT_ID" >> .tooling.env; \
	echo "" >> .tooling.env; \
	echo "Created .tooling.env"; \
	echo "  PROJECT_ID: $$PROJECT_ID"; \
	echo ""; \
	echo "Setup complete!"; \
	echo ""; \
	echo "Next steps:"; \
	echo "  1. Add devcontainer tooling: make tooling.add NAME=devcontainer"; \
	echo "  2. Set up devcontainer: make devcontainer.setup"; \
	echo "  3. Start development: make devc.up"; \
	echo ""; \
	echo "Run 'make help' to see all available commands."; \
	echo ""