## Project initialization and setup tasks
## Variables are defined in make/commons.mk

.PHONY: setup setup.project

setup.project: ## Generate unique project ID (non-interactive)
	@if [ -f .tooling.env ]; then \
		echo ".tooling.env already exists"; \
		source .tooling.env; \
		echo "  PROJECT_ID: $$PROJECT_ID"; \
	else \
		echo "Generating unique project identifier..."; \
		PROJECT_ID=$$(echo "$(REPO_DIRNAME)-$$(echo -n $(REPO_ROOT) | sha256sum | cut -c1-8)"); \
		echo "# Project Tooling Configuration" > .tooling.env; \
		echo "# Auto-generated by 'make setup.project'" >> .tooling.env; \
		echo "# DO NOT COMMIT - contains local checkout-specific settings" >> .tooling.env; \
		echo "" >> .tooling.env; \
		echo "# Unique project identifier" >> .tooling.env; \
		echo "PROJECT_ID=$$PROJECT_ID" >> .tooling.env; \
		echo "" >> .tooling.env; \
		echo "# Docker Compose project name" >> .tooling.env; \
		echo "COMPOSE_PROJECT_NAME=$$PROJECT_ID" >> .tooling.env; \
		echo "" >> .tooling.env; \
		echo "Created .tooling.env"; \
		echo "  PROJECT_ID: $$PROJECT_ID"; \
	fi

setup: ## Interactive setup with project rename and git cleanup
	@echo "repo-base - Interactive Project Setup"
	@echo ""
	@echo "This will:"
	@echo "  1. Ask for your project name"
	@echo "  2. Remove .git directory (start fresh)"
	@echo "  3. Generate .tooling.env with unique PROJECT_ID"
	@echo "  4. Rename the repository directory (if needed)"
	@echo ""
	@read -p "Current directory: $(REPO_DIRNAME). Enter new project name [$(REPO_DIRNAME)]: " project_name; \
	project_name=$${project_name:-$(REPO_DIRNAME)}; \
	echo ""; \
	echo "Project name: $$project_name"; \
	echo ""; \
	echo "Removing .git directory..."; \
	if [ -d .git ]; then \
		rm -rf .git; \
		echo ".git directory removed"; \
	else \
		echo "(no .git directory found)"; \
	fi; \
	echo ""; \
	echo "Generating .tooling.env..."; \
	parent_dir=$$(dirname $(REPO_ROOT)); \
	new_path="$$parent_dir/$$project_name"; \
	PROJECT_ID=$$(echo "$$project_name-$$(echo -n $$new_path | sha256sum | cut -c1-8)"); \
	echo "# Project Tooling Configuration" >  .tooling.env; \
	echo "# Auto-generated by 'make setup'" >> .tooling.env; \
	echo "# DO NOT COMMIT - contains local checkout-specific settings" >> .tooling.env; \
	echo "" >> .tooling.env; \
	echo "# Unique project identifier" >> .tooling.env; \
	echo "PROJECT_ID=$$PROJECT_ID" >> .tooling.env; \
	echo "" >> .tooling.env; \
	echo "# Docker Compose project name" >> .tooling.env; \
	echo "COMPOSE_PROJECT_NAME=$$PROJECT_ID" >> .tooling.env; \
	echo "" >> .tooling.env; \
	echo "Created .tooling.env"; \
	echo "  PROJECT_ID: $$PROJECT_ID"; \
	echo ""; \
	if [ "$$project_name" != "$(REPO_DIRNAME)" ]; then \
		echo "Renaming directory to $$project_name..."; \
		if [ -d "$$new_path" ]; then \
			echo "Error: Directory $$new_path already exists!"; \
			exit 1; \
		fi; \
		mv $(REPO_ROOT) $$new_path; \
		echo "Directory renamed"; \
		echo ""; \
		echo "Setup complete!";\
		echo "";\
		echo "Your working directory has moved!";\
		echo "   Run: cd $$new_path";\
		echo "";\
		echo "Next steps:";\
		echo "  1. cd $$new_path";\
		echo "  2. git init && git add . && git commit -m 'Initial commit'";\
		echo "  3. make devc.up";\
		echo "";\
	else \
		echo "Setup complete!";\
		echo "";\
		echo "Next steps:";\
		echo "  1. git init && git add . && git commit -m 'Initial commit'";\
		echo "  2. make devc.up";\
		echo "  3. make devc.shell";\
		echo "";\
	fi; \
	echo "Run 'make help' to see all available commands."; \
	echo ""